// <auto-generated />
namespace uniManageSys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class stringimage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stringimage));
        
        string IMigrationMetadata.Id
        {
            get { return "201601262033010_stringimage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
