// <auto-generated />
namespace uniManageSys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class httpimage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(httpimage));
        
        string IMigrationMetadata.Id
        {
            get { return "201601262034123_httpimage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
