// <auto-generated />
namespace uniManageSys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class phiradd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phiradd));
        
        string IMigrationMetadata.Id
        {
            get { return "201601262028322_phiradd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
